- hosts: windows
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: "Simulate connection failure"
      lineinfile:
        path: c:\Windows\System32\drivers\etc\hosts
        line: 127.0.0.1 bit.ly
      tags:
      - service_down
        
    - name: "Restore service"
      lineinfile:
        path: \Windows\System32\drivers\etc\hosts
        line: 127.0.0.1 bit.ly
        state: absent
      tags:
      - service_up
