- hosts: localhost
  vars:
    - github_token: "YOUR TOKEN HERE"
    - ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Create a GitHub Repo
      github_repo:
        github_auth_key: {% raw %} "{{github_token}}" {% endraw %}
        username: "YOUR GITHUB USERNAME HERE"
        name: "Hello-World"
        description: "First repo created with custom Ansible module"
        private: yes
        has_issues: no
        has_wiki: no
        has_downloads: no
        state: present
      register: result
